### ISSUE TITLE
File encoding issue in tos_success input

### ISSUE THREAD

**Issue by SchallerSpace** [pirl-lpl/hirise-tools#4]
The second and third items in #2 are not, after all, side effects of the first item. If an input file were exported as a CSV from Excel, it might be encoded as Mac Roman or Latin-1 (ISO-8859-1) rather than UTF-8 as might be expected. In this case, the WTH parsing fails out like so:

```
Traceback (most recent call last):
 File "/Users/kblock/hirise-tools/CIPP/tos_success.py", line 84, in <module>
   sys.exit(main())
 File "/Users/kblock/hirise-tools/CIPP/tos_success.py", line 62, in main
   for row in wthreader:
 File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
   (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 1268: invalid continuation byte
```

We can force the encoding on WTH read to `latin_1` or `mac_roman` and the file imports just fine.

**Comment by SchallerSpace** [comment]
This brings into the light an interesting UX problem: To some "CSV" means just a plain ol' text file that is edited in whatever plain ol' text editor and happens to have lines that are records with fields separate by commas. To others, it might be a specific format exported by Excel, and some versions of Excel might export in one encoding while others might use a different one.

In this case, Excel exported either `latin_1` or `mac_roman` (they seem to be the same as far as Python and the particular WTH file care), which caused the above exception when using the default (UTF-8, presumably) encoding on the `open` function.

Mac Roman vs. Latin 1/ISO-8859-1: https://en.wikipedia.org/wiki/ISO/IEC_8859-1#Mac_Roman

I think it's worth trying to handle all three here, plus adding some help language to make it clear what the input file types are.

**Comment by SchallerSpace** [comment]
(This is going way beyond the scope of the original project here, but it's an interesting problem to me.) (Plus it's a chance to do some Python programming without knowing jack about Python.)

**Comment by SchallerSpace** [comment]
Added a function `read_file` to try various encodings until one doesn't throw.

```python
def read_file(filename):
    """Read a file, trying one of several encodings."""
    lines = []
    for encoding in [None, "latin_1", "mac_roman"]:
        try:
            with open(filename, newline='', encoding=encoding) as file:
                lines = file.read().splitlines()
        except:
            pass
        if len(lines) > 0:
            break
    return lines
```

This undoes the very nice and concise

```python
with open(file) as handle:
    csvfile = csv.reader(handle)
    for row in csvfile:
        # do a thing
```

and I'm not 100% confident this is the Python way here as opposed to an obviously Java programmer doing something in Python... But it does handle Latin-1 encoded files.

**Comment by SchallerSpace** [comment]
Mm, coulda used a `else:` instead of `if len(lines) > 0:` to the same effect.

**Comment by rbeyer** [comment]
Hmm, yeah, I think I'd do that just a little differently.  File encoding stinks.

I want to help, but I need files that fail for me with the current tos_success.py in master.  The files you linked in #2 don't have that problem (possibly because they weren't problem files, or maybe because during download from GitHub the system fixed the encoding, not sure).  Please send me problem files, or describe how to produce them.

When I try and 'save as CSV' in Excel, it explicitly says UTF-8 in that option line.  Are you guys still using an elderly version of Excel or something?

**Comment by SchallerSpace** [comment]
Reference files emailed. I'm mildly uncomfortable pushing a multi-team IPTF into GitHub here; the ones I attached to #2 I thoroughly sanitized, but I'm not convinced doing so here will preserve the ISO-8859-1 elements that are breaking `tos_success.py`.

People use wildly different versions of Excel, even when their home institution supplies the latest and greatest, which is the case here. I can't make my Excel do this either! And it's very explicit about encodings now.

**Comment by guymac** [comment]
fwiw I think that approach (for/try) is quite reasonable. Thought it would be interesting to see how the the big cats do it, see https://github.com/chardet/chardet/blob/master/chardet/universaldetector.py

**Comment by SchallerSpace** [comment]
I tested Ross's update to this against my reference ISO-8859-1 case and it passes. I think we can probably modify to a for/try model if we ever run into a Cyrillic or Japanese encoding, e.g., an encoding that is neither the system default nor ISO-8859-1.
