### ISSUE TITLE
python3 print changes

### ISSUE THREAD

**Issue by SchallerSpace** [pirl-lpl/hirise-tools#5]
Right, python 3 changed how print works, so lines like

```python
print >>sys.stderr, "blah"
```

no longer work. Gotta switch to either of these:

```python
print("blah", file=sys.stderr)
sys.stderr.write("blah")
```

**Comment by rbeyer** [comment]
Exactly what conditions would allow this Issue to be closed?

Or what discussion are you looking for?

Yes, 'print' was changed from a keyword to a built-in function in Python 3.

**Comment by SchallerSpace** [comment]
Simply replacing the Python 2 prints with Python 3 would do it. Seems like the preferred way is

```python
print("blah", file=sys.stderr)
```

This is maybe a super minor thing, maybe not worthy of an issue? (I tend to throw any kind of to-do-ish problem-fixer thing into an issue in HiPlan and PLAN-C, just so I don't forget.) (Also, I picked this up and handled it this morning but absolutely failed to assign it to myself. Same with #4.)

**Comment by rbeyer** [comment]
OH!

So the real issue you should have opened should have gone something like this:

Chris: Ross, why is tos_success.py written with a bunch of Python2 print statements, the use of the outdated optparse library, and a ham-fisted approach to painstakingly return a 'man' page and a custom Usage exception?  It's written so differently from the other command line programs you committed which run just fine with Python 3?

Ross: Wha?  Oh, shorts.  You got me.  I wrote that last year before I had a good head for Python 3.  Let me clean that up, so everything is consistent at least.

But that's not what happened.  Okay, once we get past this encoding commit, I'll clean it up.
